version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rob2_db
      POSTGRES_USER: rob2_user
      POSTGRES_PASSWORD: rob2_pass
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../backend/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rob2_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://rob2_user:rob2_pass@db:5432/rob2_db
      SECRET_KEY: devsecret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../domain:/usr/src/app/domain:ro
      - ../mapeamento.xlsx.yaml:/usr/src/app/mapeamento.xlsx.yaml:ro

  frontend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ../frontend:/usr/src/app
      - frontend-node-modules:/usr/src/app/node_modules
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
  frontend-node-modules:
